name: beamspy
channels:
  - conda-forge
  - bioconda
dependencies:
 - numpy=1.17.1
 - scipy=1.3.1
 - requests=2.22.0
 - networkx=2.4
 - pandas=0.25.0
 - matplotlib=3.1.1
 - seaborn=0.9.0
 - pyteomics=4.1.2
 - biopython=1.74
 - pyside2=5.13.1
 - tqdm
