# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui',
# licensing of 'form.ui' applies.
#
# Created: Thu Dec  3 21:58:30 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(974, 775)
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(6, 5, 961, 731))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 959, 729))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_general = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_general.setTitle("")
        self.groupBox_general.setObjectName("groupBox_general")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_general)
        self.gridLayout_3.setContentsMargins(10, 5, 10, 5)
        self.gridLayout_3.setVerticalSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_peaklist = QtWidgets.QPushButton(self.groupBox_general)
        self.pushButton_peaklist.setEnabled(True)
        self.pushButton_peaklist.setMinimumSize(QtCore.QSize(95, 23))
        self.pushButton_peaklist.setMaximumSize(QtCore.QSize(95, 16777215))
        self.pushButton_peaklist.setObjectName("pushButton_peaklist")
        self.gridLayout_3.addWidget(self.pushButton_peaklist, 5, 2, 1, 1)
        self.pushButton_graph = QtWidgets.QPushButton(self.groupBox_general)
        self.pushButton_graph.setEnabled(True)
        self.pushButton_graph.setMinimumSize(QtCore.QSize(95, 23))
        self.pushButton_graph.setMaximumSize(QtCore.QSize(95, 16777215))
        self.pushButton_graph.setObjectName("pushButton_graph")
        self.gridLayout_3.addWidget(self.pushButton_graph, 5, 6, 1, 1)
        self.pushButton_default_adduct_library = QtWidgets.QPushButton(self.groupBox_general)
        self.pushButton_default_adduct_library.setEnabled(True)
        self.pushButton_default_adduct_library.setMinimumSize(QtCore.QSize(95, 23))
        self.pushButton_default_adduct_library.setMaximumSize(QtCore.QSize(95, 16777215))
        self.pushButton_default_adduct_library.setObjectName("pushButton_default_adduct_library")
        self.gridLayout_3.addWidget(self.pushButton_default_adduct_library, 7, 6, 1, 1)
        self.lineEdit_intensity_matrix = QtWidgets.QLineEdit(self.groupBox_general)
        self.lineEdit_intensity_matrix.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_intensity_matrix.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_intensity_matrix.setText("")
        self.lineEdit_intensity_matrix.setReadOnly(True)
        self.lineEdit_intensity_matrix.setObjectName("lineEdit_intensity_matrix")
        self.gridLayout_3.addWidget(self.lineEdit_intensity_matrix, 7, 1, 1, 1)
        self.lineEdit_graph = QtWidgets.QLineEdit(self.groupBox_general)
        self.lineEdit_graph.setEnabled(True)
        self.lineEdit_graph.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_graph.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_graph.setText("")
        self.lineEdit_graph.setReadOnly(True)
        self.lineEdit_graph.setObjectName("lineEdit_graph")
        self.gridLayout_3.addWidget(self.lineEdit_graph, 5, 5, 1, 1)
        self.label_graph = QtWidgets.QLabel(self.groupBox_general)
        self.label_graph.setEnabled(True)
        self.label_graph.setObjectName("label_graph")
        self.gridLayout_3.addWidget(self.label_graph, 5, 3, 1, 1)
        self.lineEdit_wd = QtWidgets.QLineEdit(self.groupBox_general)
        self.lineEdit_wd.setEnabled(True)
        self.lineEdit_wd.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_wd.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_wd.setText("")
        self.lineEdit_wd.setReadOnly(True)
        self.lineEdit_wd.setObjectName("lineEdit_wd")
        self.gridLayout_3.addWidget(self.lineEdit_wd, 4, 1, 1, 1)
        self.pushButton_sql_database = QtWidgets.QPushButton(self.groupBox_general)
        self.pushButton_sql_database.setEnabled(True)
        self.pushButton_sql_database.setMinimumSize(QtCore.QSize(95, 23))
        self.pushButton_sql_database.setMaximumSize(QtCore.QSize(95, 16777215))
        self.pushButton_sql_database.setObjectName("pushButton_sql_database")
        self.gridLayout_3.addWidget(self.pushButton_sql_database, 4, 6, 1, 1)
        self.lineEdit_sql_database = QtWidgets.QLineEdit(self.groupBox_general)
        self.lineEdit_sql_database.setEnabled(True)
        self.lineEdit_sql_database.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_sql_database.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_sql_database.setText("")
        self.lineEdit_sql_database.setReadOnly(True)
        self.lineEdit_sql_database.setObjectName("lineEdit_sql_database")
        self.gridLayout_3.addWidget(self.lineEdit_sql_database, 4, 5, 1, 1)
        self.lineEdit_peaklist = QtWidgets.QLineEdit(self.groupBox_general)
        self.lineEdit_peaklist.setEnabled(True)
        self.lineEdit_peaklist.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_peaklist.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_peaklist.setText("")
        self.lineEdit_peaklist.setReadOnly(True)
        self.lineEdit_peaklist.setObjectName("lineEdit_peaklist")
        self.gridLayout_3.addWidget(self.lineEdit_peaklist, 5, 1, 1, 1)
        self.pushButton_wd = QtWidgets.QPushButton(self.groupBox_general)
        self.pushButton_wd.setEnabled(True)
        self.pushButton_wd.setMinimumSize(QtCore.QSize(95, 23))
        self.pushButton_wd.setMaximumSize(QtCore.QSize(95, 16777215))
        self.pushButton_wd.setObjectName("pushButton_wd")
        self.gridLayout_3.addWidget(self.pushButton_wd, 4, 2, 1, 1)
        self.label_default_adduct_library = QtWidgets.QLabel(self.groupBox_general)
        self.label_default_adduct_library.setEnabled(True)
        self.label_default_adduct_library.setObjectName("label_default_adduct_library")
        self.gridLayout_3.addWidget(self.label_default_adduct_library, 7, 3, 1, 1)
        self.label_intensity_matrix = QtWidgets.QLabel(self.groupBox_general)
        self.label_intensity_matrix.setObjectName("label_intensity_matrix")
        self.gridLayout_3.addWidget(self.label_intensity_matrix, 7, 0, 1, 1)
        self.lineEdit_default_adduct_library = QtWidgets.QLineEdit(self.groupBox_general)
        self.lineEdit_default_adduct_library.setEnabled(True)
        self.lineEdit_default_adduct_library.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_default_adduct_library.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_default_adduct_library.setReadOnly(True)
        self.lineEdit_default_adduct_library.setObjectName("lineEdit_default_adduct_library")
        self.gridLayout_3.addWidget(self.lineEdit_default_adduct_library, 7, 5, 1, 1)
        self.pushButton_peak_matrix = QtWidgets.QPushButton(self.groupBox_general)
        self.pushButton_peak_matrix.setEnabled(True)
        self.pushButton_peak_matrix.setMinimumSize(QtCore.QSize(95, 23))
        self.pushButton_peak_matrix.setMaximumSize(QtCore.QSize(95, 16777215))
        self.pushButton_peak_matrix.setObjectName("pushButton_peak_matrix")
        self.gridLayout_3.addWidget(self.pushButton_peak_matrix, 7, 2, 1, 1)
        self.label_ion_mode = QtWidgets.QLabel(self.groupBox_general)
        self.label_ion_mode.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_ion_mode.setObjectName("label_ion_mode")
        self.gridLayout_3.addWidget(self.label_ion_mode, 7, 7, 1, 1)
        self.comboBox_ion_mode = QtWidgets.QComboBox(self.groupBox_general)
        self.comboBox_ion_mode.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_ion_mode.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_ion_mode.setObjectName("comboBox_ion_mode")
        self.comboBox_ion_mode.addItem("")
        self.comboBox_ion_mode.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_ion_mode, 7, 8, 1, 1)
        self.label_sql_database = QtWidgets.QLabel(self.groupBox_general)
        self.label_sql_database.setEnabled(True)
        self.label_sql_database.setObjectName("label_sql_database")
        self.gridLayout_3.addWidget(self.label_sql_database, 4, 3, 1, 1)
        self.label_peaklist = QtWidgets.QLabel(self.groupBox_general)
        self.label_peaklist.setEnabled(True)
        self.label_peaklist.setObjectName("label_peaklist")
        self.gridLayout_3.addWidget(self.label_peaklist, 5, 0, 1, 1)
        self.label_wd = QtWidgets.QLabel(self.groupBox_general)
        self.label_wd.setEnabled(True)
        self.label_wd.setObjectName("label_wd")
        self.gridLayout_3.addWidget(self.label_wd, 4, 0, 1, 1)
        self.label_data_files = QtWidgets.QLabel(self.groupBox_general)
        self.label_data_files.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label_data_files.setFont(font)
        self.label_data_files.setObjectName("label_data_files")
        self.gridLayout_3.addWidget(self.label_data_files, 3, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox_general)
        self.groupBox_group_features = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_group_features.setTitle("")
        self.groupBox_group_features.setObjectName("groupBox_group_features")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_group_features)
        self.gridLayout_4.setContentsMargins(10, 5, 10, 5)
        self.gridLayout_4.setVerticalSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.doubleSpinBox_block = QtWidgets.QDoubleSpinBox(self.groupBox_group_features)
        self.doubleSpinBox_block.setDecimals(0)
        self.doubleSpinBox_block.setMaximum(100000000.0)
        self.doubleSpinBox_block.setSingleStep(1000.0)
        self.doubleSpinBox_block.setProperty("value", 5000.0)
        self.doubleSpinBox_block.setObjectName("doubleSpinBox_block")
        self.gridLayout_4.addWidget(self.doubleSpinBox_block, 9, 5, 1, 1)
        self.doubleSpinBox_ncpus = QtWidgets.QDoubleSpinBox(self.groupBox_group_features)
        self.doubleSpinBox_ncpus.setDecimals(0)
        self.doubleSpinBox_ncpus.setMaximum(10000.0)
        self.doubleSpinBox_ncpus.setSingleStep(1.0)
        self.doubleSpinBox_ncpus.setProperty("value", 1.0)
        self.doubleSpinBox_ncpus.setObjectName("doubleSpinBox_ncpus")
        self.gridLayout_4.addWidget(self.doubleSpinBox_ncpus, 3, 5, 1, 1)
        self.label_grouping_method = QtWidgets.QLabel(self.groupBox_group_features)
        self.label_grouping_method.setEnabled(True)
        self.label_grouping_method.setObjectName("label_grouping_method")
        self.gridLayout_4.addWidget(self.label_grouping_method, 3, 2, 1, 1)
        self.doubleSpinBox_coefficent = QtWidgets.QDoubleSpinBox(self.groupBox_group_features)
        self.doubleSpinBox_coefficent.setMaximum(1.0)
        self.doubleSpinBox_coefficent.setSingleStep(0.1)
        self.doubleSpinBox_coefficent.setProperty("value", 0.7)
        self.doubleSpinBox_coefficent.setObjectName("doubleSpinBox_coefficent")
        self.gridLayout_4.addWidget(self.doubleSpinBox_coefficent, 9, 1, 1, 1)
        self.checkBox_group_features = QtWidgets.QCheckBox(self.groupBox_group_features)
        self.checkBox_group_features.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.checkBox_group_features.setFont(font)
        self.checkBox_group_features.setChecked(True)
        self.checkBox_group_features.setObjectName("checkBox_group_features")
        self.gridLayout_4.addWidget(self.checkBox_group_features, 0, 0, 1, 2)
        self.label_tool_p_value = QtWidgets.QLabel(self.groupBox_group_features)
        self.label_tool_p_value.setEnabled(True)
        self.label_tool_p_value.setObjectName("label_tool_p_value")
        self.gridLayout_4.addWidget(self.label_tool_p_value, 9, 2, 1, 1)
        self.label_max_rt = QtWidgets.QLabel(self.groupBox_group_features)
        self.label_max_rt.setEnabled(True)
        self.label_max_rt.setObjectName("label_max_rt")
        self.gridLayout_4.addWidget(self.label_max_rt, 3, 0, 1, 1)
        self.doubleSpinBox_max_rt = QtWidgets.QDoubleSpinBox(self.groupBox_group_features)
        self.doubleSpinBox_max_rt.setMaximum(9999999.0)
        self.doubleSpinBox_max_rt.setProperty("value", 5.0)
        self.doubleSpinBox_max_rt.setObjectName("doubleSpinBox_max_rt")
        self.gridLayout_4.addWidget(self.doubleSpinBox_max_rt, 3, 1, 1, 1)
        self.doubleSpinBox_p_value = QtWidgets.QDoubleSpinBox(self.groupBox_group_features)
        self.doubleSpinBox_p_value.setDecimals(10)
        self.doubleSpinBox_p_value.setMaximum(1.0)
        self.doubleSpinBox_p_value.setSingleStep(0.01)
        self.doubleSpinBox_p_value.setProperty("value", 0.01)
        self.doubleSpinBox_p_value.setObjectName("doubleSpinBox_p_value")
        self.gridLayout_4.addWidget(self.doubleSpinBox_p_value, 9, 3, 1, 1)
        self.label_tool_coefficient = QtWidgets.QLabel(self.groupBox_group_features)
        self.label_tool_coefficient.setEnabled(True)
        self.label_tool_coefficient.setObjectName("label_tool_coefficient")
        self.gridLayout_4.addWidget(self.label_tool_coefficient, 9, 0, 1, 1)
        self.comboBox_grouping_method = QtWidgets.QComboBox(self.groupBox_group_features)
        self.comboBox_grouping_method.setObjectName("comboBox_grouping_method")
        self.comboBox_grouping_method.addItem("")
        self.comboBox_grouping_method.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_grouping_method, 3, 3, 1, 1)
        self.label_grouping_ncpus = QtWidgets.QLabel(self.groupBox_group_features)
        self.label_grouping_ncpus.setEnabled(True)
        self.label_grouping_ncpus.setObjectName("label_grouping_ncpus")
        self.gridLayout_4.addWidget(self.label_grouping_ncpus, 3, 4, 1, 1)
        self.label_grouping_block = QtWidgets.QLabel(self.groupBox_group_features)
        self.label_grouping_block.setEnabled(True)
        self.label_grouping_block.setObjectName("label_grouping_block")
        self.gridLayout_4.addWidget(self.label_grouping_block, 9, 4, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_group_features)
        self.groupBox_annotate_peak_patterns = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_annotate_peak_patterns.setTitle("")
        self.groupBox_annotate_peak_patterns.setObjectName("groupBox_annotate_peak_patterns")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_annotate_peak_patterns)
        self.gridLayout.setContentsMargins(10, 5, 10, 5)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_isotopes = QtWidgets.QPushButton(self.groupBox_annotate_peak_patterns)
        self.pushButton_isotopes.setEnabled(True)
        self.pushButton_isotopes.setMinimumSize(QtCore.QSize(95, 23))
        self.pushButton_isotopes.setMaximumSize(QtCore.QSize(95, 16777215))
        self.pushButton_isotopes.setObjectName("pushButton_isotopes")
        self.gridLayout.addWidget(self.pushButton_isotopes, 6, 4, 1, 1)
        self.label_max_monomer_units = QtWidgets.QLabel(self.groupBox_annotate_peak_patterns)
        self.label_max_monomer_units.setEnabled(True)
        self.label_max_monomer_units.setMinimumSize(QtCore.QSize(110, 0))
        self.label_max_monomer_units.setObjectName("label_max_monomer_units")
        self.gridLayout.addWidget(self.label_max_monomer_units, 6, 7, 1, 1)
        self.checkBox_neutral_losses = QtWidgets.QCheckBox(self.groupBox_annotate_peak_patterns)
        self.checkBox_neutral_losses.setEnabled(True)
        self.checkBox_neutral_losses.setChecked(True)
        self.checkBox_neutral_losses.setObjectName("checkBox_neutral_losses")
        self.gridLayout.addWidget(self.checkBox_neutral_losses, 4, 5, 1, 1)
        self.pushButton_neutral_losses = QtWidgets.QPushButton(self.groupBox_annotate_peak_patterns)
        self.pushButton_neutral_losses.setEnabled(True)
        self.pushButton_neutral_losses.setMinimumSize(QtCore.QSize(63, 23))
        self.pushButton_neutral_losses.setMaximumSize(QtCore.QSize(95, 16777215))
        self.pushButton_neutral_losses.setObjectName("pushButton_neutral_losses")
        self.gridLayout.addWidget(self.pushButton_neutral_losses, 6, 6, 1, 1)
        self.checkBox_isotopes = QtWidgets.QCheckBox(self.groupBox_annotate_peak_patterns)
        self.checkBox_isotopes.setEnabled(True)
        self.checkBox_isotopes.setChecked(True)
        self.checkBox_isotopes.setObjectName("checkBox_isotopes")
        self.gridLayout.addWidget(self.checkBox_isotopes, 4, 3, 1, 1)
        self.lineEdit_isotopes = QtWidgets.QLineEdit(self.groupBox_annotate_peak_patterns)
        self.lineEdit_isotopes.setEnabled(True)
        self.lineEdit_isotopes.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEdit_isotopes.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEdit_isotopes.setReadOnly(True)
        self.lineEdit_isotopes.setObjectName("lineEdit_isotopes")
        self.gridLayout.addWidget(self.lineEdit_isotopes, 6, 3, 1, 1)
        self.checkBox_annotate_peak_patterns = QtWidgets.QCheckBox(self.groupBox_annotate_peak_patterns)
        self.checkBox_annotate_peak_patterns.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.checkBox_annotate_peak_patterns.setFont(font)
        self.checkBox_annotate_peak_patterns.setChecked(True)
        self.checkBox_annotate_peak_patterns.setObjectName("checkBox_annotate_peak_patterns")
        self.gridLayout.addWidget(self.checkBox_annotate_peak_patterns, 0, 0, 1, 2)
        self.checkBox_adduct_library = QtWidgets.QCheckBox(self.groupBox_annotate_peak_patterns)
        self.checkBox_adduct_library.setEnabled(True)
        self.checkBox_adduct_library.setChecked(True)
        self.checkBox_adduct_library.setObjectName("checkBox_adduct_library")
        self.gridLayout.addWidget(self.checkBox_adduct_library, 4, 0, 1, 1)
        self.checkBox_oligomers = QtWidgets.QCheckBox(self.groupBox_annotate_peak_patterns)
        self.checkBox_oligomers.setEnabled(True)
        self.checkBox_oligomers.setChecked(False)
        self.checkBox_oligomers.setObjectName("checkBox_oligomers")
        self.gridLayout.addWidget(self.checkBox_oligomers, 4, 7, 1, 1)
        self.label_pp_ppm_tolerance = QtWidgets.QLabel(self.groupBox_annotate_peak_patterns)
        self.label_pp_ppm_tolerance.setEnabled(True)
        self.label_pp_ppm_tolerance.setObjectName("label_pp_ppm_tolerance")
        self.gridLayout.addWidget(self.label_pp_ppm_tolerance, 10, 0, 1, 2)
        self.lineEdit_neutral_losses = QtWidgets.QLineEdit(self.groupBox_annotate_peak_patterns)
        self.lineEdit_neutral_losses.setEnabled(True)
        self.lineEdit_neutral_losses.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEdit_neutral_losses.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEdit_neutral_losses.setReadOnly(True)
        self.lineEdit_neutral_losses.setObjectName("lineEdit_neutral_losses")
        self.gridLayout.addWidget(self.lineEdit_neutral_losses, 6, 5, 1, 1)
        self.spinBox_max_monomer_units = QtWidgets.QSpinBox(self.groupBox_annotate_peak_patterns)
        self.spinBox_max_monomer_units.setMinimum(2)
        self.spinBox_max_monomer_units.setMaximum(1000000)
        self.spinBox_max_monomer_units.setProperty("value", 2)
        self.spinBox_max_monomer_units.setDisplayIntegerBase(10)
        self.spinBox_max_monomer_units.setObjectName("spinBox_max_monomer_units")
        self.gridLayout.addWidget(self.spinBox_max_monomer_units, 6, 8, 1, 1)
        self.lineEdit_adduct_library = QtWidgets.QLineEdit(self.groupBox_annotate_peak_patterns)
        self.lineEdit_adduct_library.setEnabled(True)
        self.lineEdit_adduct_library.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEdit_adduct_library.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEdit_adduct_library.setReadOnly(True)
        self.lineEdit_adduct_library.setObjectName("lineEdit_adduct_library")
        self.gridLayout.addWidget(self.lineEdit_adduct_library, 6, 0, 1, 1)
        self.pushButton_adduct_library = QtWidgets.QPushButton(self.groupBox_annotate_peak_patterns)
        self.pushButton_adduct_library.setEnabled(True)
        self.pushButton_adduct_library.setMinimumSize(QtCore.QSize(95, 23))
        self.pushButton_adduct_library.setMaximumSize(QtCore.QSize(95, 16777215))
        self.pushButton_adduct_library.setObjectName("pushButton_adduct_library")
        self.gridLayout.addWidget(self.pushButton_adduct_library, 6, 1, 1, 2)
        self.doubleSpinBox_pp_ppm_error = QtWidgets.QDoubleSpinBox(self.groupBox_annotate_peak_patterns)
        self.doubleSpinBox_pp_ppm_error.setMaximum(100000.0)
        self.doubleSpinBox_pp_ppm_error.setProperty("value", 5.0)
        self.doubleSpinBox_pp_ppm_error.setObjectName("doubleSpinBox_pp_ppm_error")
        self.gridLayout.addWidget(self.doubleSpinBox_pp_ppm_error, 10, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_annotate_peak_patterns)
        self.groupBox_annotate_molecular_formulae = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_annotate_molecular_formulae.setTitle("")
        self.groupBox_annotate_molecular_formulae.setObjectName("groupBox_annotate_molecular_formulae")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_annotate_molecular_formulae)
        self.gridLayout_7.setContentsMargins(10, 5, 10, 5)
        self.gridLayout_7.setVerticalSpacing(5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit_filename_mf = QtWidgets.QLineEdit(self.groupBox_annotate_molecular_formulae)
        self.lineEdit_filename_mf.setEnabled(False)
        self.lineEdit_filename_mf.setText("")
        self.lineEdit_filename_mf.setReadOnly(True)
        self.lineEdit_filename_mf.setObjectName("lineEdit_filename_mf")
        self.gridLayout_7.addWidget(self.lineEdit_filename_mf, 2, 1, 1, 1)
        self.doubleSpinBox_mf_ppm_error = QtWidgets.QDoubleSpinBox(self.groupBox_annotate_molecular_formulae)
        self.doubleSpinBox_mf_ppm_error.setEnabled(False)
        self.doubleSpinBox_mf_ppm_error.setMaximum(100000.0)
        self.doubleSpinBox_mf_ppm_error.setProperty("value", 5.0)
        self.doubleSpinBox_mf_ppm_error.setObjectName("doubleSpinBox_mf_ppm_error")
        self.gridLayout_7.addWidget(self.doubleSpinBox_mf_ppm_error, 2, 4, 1, 1)
        self.pushButton_filename_mf = QtWidgets.QPushButton(self.groupBox_annotate_molecular_formulae)
        self.pushButton_filename_mf.setEnabled(False)
        self.pushButton_filename_mf.setMinimumSize(QtCore.QSize(63, 23))
        self.pushButton_filename_mf.setFlat(False)
        self.pushButton_filename_mf.setObjectName("pushButton_filename_mf")
        self.gridLayout_7.addWidget(self.pushButton_filename_mf, 2, 2, 1, 1)
        self.label_max_mz = QtWidgets.QLabel(self.groupBox_annotate_molecular_formulae)
        self.label_max_mz.setEnabled(False)
        self.label_max_mz.setObjectName("label_max_mz")
        self.gridLayout_7.addWidget(self.label_max_mz, 1, 3, 1, 1)
        self.checkBox_mf_pp_rules = QtWidgets.QCheckBox(self.groupBox_annotate_molecular_formulae)
        self.checkBox_mf_pp_rules.setEnabled(False)
        self.checkBox_mf_pp_rules.setChecked(True)
        self.checkBox_mf_pp_rules.setObjectName("checkBox_mf_pp_rules")
        self.gridLayout_7.addWidget(self.checkBox_mf_pp_rules, 1, 5, 1, 1)
        self.spinBox_max_mz = QtWidgets.QSpinBox(self.groupBox_annotate_molecular_formulae)
        self.spinBox_max_mz.setEnabled(False)
        self.spinBox_max_mz.setMaximum(1000000)
        self.spinBox_max_mz.setProperty("value", 500)
        self.spinBox_max_mz.setDisplayIntegerBase(10)
        self.spinBox_max_mz.setObjectName("spinBox_max_mz")
        self.gridLayout_7.addWidget(self.spinBox_max_mz, 1, 4, 1, 1)
        self.label_mf_ppm_tolerance = QtWidgets.QLabel(self.groupBox_annotate_molecular_formulae)
        self.label_mf_ppm_tolerance.setEnabled(False)
        self.label_mf_ppm_tolerance.setObjectName("label_mf_ppm_tolerance")
        self.gridLayout_7.addWidget(self.label_mf_ppm_tolerance, 2, 3, 1, 1)
        self.comboBox_source_mf = QtWidgets.QComboBox(self.groupBox_annotate_molecular_formulae)
        self.comboBox_source_mf.setEnabled(False)
        self.comboBox_source_mf.setObjectName("comboBox_source_mf")
        self.comboBox_source_mf.addItem("")
        self.comboBox_source_mf.addItem("")
        self.gridLayout_7.addWidget(self.comboBox_source_mf, 1, 1, 1, 1)
        self.label_filename_mf = QtWidgets.QLabel(self.groupBox_annotate_molecular_formulae)
        self.label_filename_mf.setEnabled(False)
        self.label_filename_mf.setObjectName("label_filename_mf")
        self.gridLayout_7.addWidget(self.label_filename_mf, 2, 0, 1, 1)
        self.checkBox_heuristic_rules = QtWidgets.QCheckBox(self.groupBox_annotate_molecular_formulae)
        self.checkBox_heuristic_rules.setEnabled(False)
        self.checkBox_heuristic_rules.setChecked(True)
        self.checkBox_heuristic_rules.setObjectName("checkBox_heuristic_rules")
        self.gridLayout_7.addWidget(self.checkBox_heuristic_rules, 2, 5, 1, 1)
        self.label_source_mf = QtWidgets.QLabel(self.groupBox_annotate_molecular_formulae)
        self.label_source_mf.setEnabled(False)
        self.label_source_mf.setObjectName("label_source_mf")
        self.gridLayout_7.addWidget(self.label_source_mf, 1, 0, 1, 1)
        self.checkBox_annotate_molecular_formulae = QtWidgets.QCheckBox(self.groupBox_annotate_molecular_formulae)
        self.checkBox_annotate_molecular_formulae.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.checkBox_annotate_molecular_formulae.setFont(font)
        self.checkBox_annotate_molecular_formulae.setCheckable(True)
        self.checkBox_annotate_molecular_formulae.setChecked(False)
        self.checkBox_annotate_molecular_formulae.setObjectName("checkBox_annotate_molecular_formulae")
        self.gridLayout_7.addWidget(self.checkBox_annotate_molecular_formulae, 0, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox_annotate_molecular_formulae)
        self.groupBox_annotate_compounds = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_annotate_compounds.setTitle("")
        self.groupBox_annotate_compounds.setObjectName("groupBox_annotate_compounds")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_annotate_compounds)
        self.gridLayout_6.setContentsMargins(10, 5, 10, 5)
        self.gridLayout_6.setVerticalSpacing(5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_filename_reference = QtWidgets.QPushButton(self.groupBox_annotate_compounds)
        self.pushButton_filename_reference.setEnabled(False)
        self.pushButton_filename_reference.setMinimumSize(QtCore.QSize(63, 23))
        self.pushButton_filename_reference.setObjectName("pushButton_filename_reference")
        self.gridLayout_6.addWidget(self.pushButton_filename_reference, 2, 2, 1, 1)
        self.lineEdit_filename_reference = QtWidgets.QLineEdit(self.groupBox_annotate_compounds)
        self.lineEdit_filename_reference.setEnabled(False)
        self.lineEdit_filename_reference.setText("")
        self.lineEdit_filename_reference.setReadOnly(True)
        self.lineEdit_filename_reference.setObjectName("lineEdit_filename_reference")
        self.gridLayout_6.addWidget(self.lineEdit_filename_reference, 2, 1, 1, 1)
        self.checkBox_cpds_pp_rules = QtWidgets.QCheckBox(self.groupBox_annotate_compounds)
        self.checkBox_cpds_pp_rules.setEnabled(True)
        self.checkBox_cpds_pp_rules.setChecked(True)
        self.checkBox_cpds_pp_rules.setObjectName("checkBox_cpds_pp_rules")
        self.gridLayout_6.addWidget(self.checkBox_cpds_pp_rules, 3, 3, 1, 1)
        self.checkBox_filename_reference = QtWidgets.QCheckBox(self.groupBox_annotate_compounds)
        self.checkBox_filename_reference.setEnabled(True)
        self.checkBox_filename_reference.setChecked(False)
        self.checkBox_filename_reference.setObjectName("checkBox_filename_reference")
        self.gridLayout_6.addWidget(self.checkBox_filename_reference, 1, 1, 1, 1)
        self.listWidget_databases = QtWidgets.QListWidget(self.groupBox_annotate_compounds)
        self.listWidget_databases.setMinimumSize(QtCore.QSize(510, 0))
        self.listWidget_databases.setMaximumSize(QtCore.QSize(16777215, 95))
        self.listWidget_databases.setObjectName("listWidget_databases")
        self.gridLayout_6.addWidget(self.listWidget_databases, 1, 0, 4, 1)
        self.doubleSpinBox_cpds_ppm_error = QtWidgets.QDoubleSpinBox(self.groupBox_annotate_compounds)
        self.doubleSpinBox_cpds_ppm_error.setMaximum(100000.0)
        self.doubleSpinBox_cpds_ppm_error.setProperty("value", 5.0)
        self.doubleSpinBox_cpds_ppm_error.setObjectName("doubleSpinBox_cpds_ppm_error")
        self.gridLayout_6.addWidget(self.doubleSpinBox_cpds_ppm_error, 3, 2, 1, 1)
        self.label_cpds_ppm_tolerance = QtWidgets.QLabel(self.groupBox_annotate_compounds)
        self.label_cpds_ppm_tolerance.setEnabled(True)
        self.label_cpds_ppm_tolerance.setObjectName("label_cpds_ppm_tolerance")
        self.gridLayout_6.addWidget(self.label_cpds_ppm_tolerance, 3, 1, 1, 1)
        self.checkBox_annotate_compounds = QtWidgets.QCheckBox(self.groupBox_annotate_compounds)
        self.checkBox_annotate_compounds.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.checkBox_annotate_compounds.setFont(font)
        self.checkBox_annotate_compounds.setChecked(True)
        self.checkBox_annotate_compounds.setObjectName("checkBox_annotate_compounds")
        self.gridLayout_6.addWidget(self.checkBox_annotate_compounds, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_annotate_compounds)
        self.groupBox_create_summary = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_create_summary.setTitle("")
        self.groupBox_create_summary.setObjectName("groupBox_create_summary")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_create_summary)
        self.gridLayout_2.setContentsMargins(10, 5, 10, 5)
        self.gridLayout_2.setVerticalSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_summary_filename = QtWidgets.QPushButton(self.groupBox_create_summary)
        self.pushButton_summary_filename.setMinimumSize(QtCore.QSize(63, 23))
        self.pushButton_summary_filename.setObjectName("pushButton_summary_filename")
        self.gridLayout_2.addWidget(self.pushButton_summary_filename, 1, 2, 1, 1)
        self.spinBox_mz_digits = QtWidgets.QSpinBox(self.groupBox_create_summary)
        self.spinBox_mz_digits.setEnabled(False)
        self.spinBox_mz_digits.setMaximum(1000000)
        self.spinBox_mz_digits.setProperty("value", 5)
        self.spinBox_mz_digits.setDisplayIntegerBase(10)
        self.spinBox_mz_digits.setObjectName("spinBox_mz_digits")
        self.gridLayout_2.addWidget(self.spinBox_mz_digits, 3, 5, 1, 1)
        self.checkBox_convert_rt = QtWidgets.QCheckBox(self.groupBox_create_summary)
        self.checkBox_convert_rt.setEnabled(True)
        self.checkBox_convert_rt.setChecked(False)
        self.checkBox_convert_rt.setObjectName("checkBox_convert_rt")
        self.gridLayout_2.addWidget(self.checkBox_convert_rt, 3, 6, 1, 1)
        self.comboBox_annotations_format = QtWidgets.QComboBox(self.groupBox_create_summary)
        self.comboBox_annotations_format.setObjectName("comboBox_annotations_format")
        self.comboBox_annotations_format.addItem("")
        self.comboBox_annotations_format.addItem("")
        self.comboBox_annotations_format.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_annotations_format, 3, 1, 1, 1)
        self.label_separator = QtWidgets.QLabel(self.groupBox_create_summary)
        self.label_separator.setEnabled(True)
        self.label_separator.setObjectName("label_separator")
        self.gridLayout_2.addWidget(self.label_separator, 1, 3, 1, 1)
        self.lineEdit_summary_filename = QtWidgets.QLineEdit(self.groupBox_create_summary)
        self.lineEdit_summary_filename.setText("")
        self.lineEdit_summary_filename.setReadOnly(True)
        self.lineEdit_summary_filename.setObjectName("lineEdit_summary_filename")
        self.gridLayout_2.addWidget(self.lineEdit_summary_filename, 1, 1, 1, 1)
        self.comboBox_convert_rt = QtWidgets.QComboBox(self.groupBox_create_summary)
        self.comboBox_convert_rt.setEnabled(False)
        self.comboBox_convert_rt.setObjectName("comboBox_convert_rt")
        self.comboBox_convert_rt.addItem("")
        self.comboBox_convert_rt.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_convert_rt, 3, 7, 1, 1)
        self.checkBox_create_summary = QtWidgets.QCheckBox(self.groupBox_create_summary)
        self.checkBox_create_summary.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.checkBox_create_summary.setFont(font)
        self.checkBox_create_summary.setChecked(True)
        self.checkBox_create_summary.setObjectName("checkBox_create_summary")
        self.gridLayout_2.addWidget(self.checkBox_create_summary, 0, 0, 1, 2)
        self.checkBox_mz_digits = QtWidgets.QCheckBox(self.groupBox_create_summary)
        self.checkBox_mz_digits.setEnabled(True)
        self.checkBox_mz_digits.setChecked(False)
        self.checkBox_mz_digits.setObjectName("checkBox_mz_digits")
        self.gridLayout_2.addWidget(self.checkBox_mz_digits, 3, 2, 1, 2)
        self.comboBox_separator = QtWidgets.QComboBox(self.groupBox_create_summary)
        self.comboBox_separator.setObjectName("comboBox_separator")
        self.comboBox_separator.addItem("")
        self.comboBox_separator.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_separator, 1, 5, 1, 1)
        self.label_summary_filename = QtWidgets.QLabel(self.groupBox_create_summary)
        self.label_summary_filename.setEnabled(True)
        self.label_summary_filename.setObjectName("label_summary_filename")
        self.gridLayout_2.addWidget(self.label_summary_filename, 1, 0, 1, 1)
        self.label_annotations_format = QtWidgets.QLabel(self.groupBox_create_summary)
        self.label_annotations_format.setEnabled(True)
        self.label_annotations_format.setObjectName("label_annotations_format")
        self.gridLayout_2.addWidget(self.label_annotations_format, 3, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_create_summary)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(860, 740, 100, 32))
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cancel.setGeometry(QtCore.QRect(760, 740, 100, 32))
        self.pushButton_cancel.setMaximumSize(QtCore.QSize(16777204, 16777215))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionExampleData = QtWidgets.QAction(MainWindow)
        self.actionExampleData.setObjectName("actionExampleData")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "BEAMSpy - Birmingham mEtabolite Annotation for Mass Spectrometry (Python package)", None, -1))
        self.pushButton_peaklist.setText(QtWidgets.QApplication.translate("MainWindow", "Browse...", None, -1))
        self.pushButton_graph.setText(QtWidgets.QApplication.translate("MainWindow", "Save as...", None, -1))
        self.pushButton_default_adduct_library.setText(QtWidgets.QApplication.translate("MainWindow", "Browse...", None, -1))
        self.label_graph.setText(QtWidgets.QApplication.translate("MainWindow", "Graph:", None, -1))
        self.pushButton_sql_database.setText(QtWidgets.QApplication.translate("MainWindow", "Save as...", None, -1))
        self.pushButton_wd.setText(QtWidgets.QApplication.translate("MainWindow", "Browse...", None, -1))
        self.label_default_adduct_library.setText(QtWidgets.QApplication.translate("MainWindow", "Adduct library:", None, -1))
        self.label_intensity_matrix.setText(QtWidgets.QApplication.translate("MainWindow", "Intensity matrix:", None, -1))
        self.lineEdit_default_adduct_library.setText(QtWidgets.QApplication.translate("MainWindow", "Use default", None, -1))
        self.pushButton_peak_matrix.setText(QtWidgets.QApplication.translate("MainWindow", "Browse...", None, -1))
        self.label_ion_mode.setText(QtWidgets.QApplication.translate("MainWindow", "Ion mode:", None, -1))
        self.comboBox_ion_mode.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Positive", None, -1))
        self.comboBox_ion_mode.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Negative", None, -1))
        self.label_sql_database.setText(QtWidgets.QApplication.translate("MainWindow", "Database:", None, -1))
        self.label_peaklist.setText(QtWidgets.QApplication.translate("MainWindow", "Peaklist:", None, -1))
        self.label_wd.setText(QtWidgets.QApplication.translate("MainWindow", "Working directory:", None, -1))
        self.label_data_files.setText(QtWidgets.QApplication.translate("MainWindow", "Data Files & General Settings", None, -1))
        self.label_grouping_method.setText(QtWidgets.QApplication.translate("MainWindow", "Grouping method:", None, -1))
        self.checkBox_group_features.setText(QtWidgets.QApplication.translate("MainWindow", "Group Features", None, -1))
        self.label_tool_p_value.setText(QtWidgets.QApplication.translate("MainWindow", "P-value threshold:", None, -1))
        self.label_max_rt.setText(QtWidgets.QApplication.translate("MainWindow", "Maximum RT difference (sec):", None, -1))
        self.label_tool_coefficient.setText(QtWidgets.QApplication.translate("MainWindow", "Coefficent threshold:", None, -1))
        self.comboBox_grouping_method.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Pearson correlation", None, -1))
        self.comboBox_grouping_method.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Spearman-rank correlation", None, -1))
        self.label_grouping_ncpus.setText(QtWidgets.QApplication.translate("MainWindow", "cpus:", None, -1))
        self.label_grouping_block.setText(QtWidgets.QApplication.translate("MainWindow", "Block size:", None, -1))
        self.pushButton_isotopes.setText(QtWidgets.QApplication.translate("MainWindow", "Browse...", None, -1))
        self.label_max_monomer_units.setText(QtWidgets.QApplication.translate("MainWindow", "Monomer Units:", None, -1))
        self.checkBox_neutral_losses.setText(QtWidgets.QApplication.translate("MainWindow", "Neutral losses", None, -1))
        self.pushButton_neutral_losses.setText(QtWidgets.QApplication.translate("MainWindow", "Browse...", None, -1))
        self.checkBox_isotopes.setText(QtWidgets.QApplication.translate("MainWindow", "Isotopes", None, -1))
        self.lineEdit_isotopes.setText(QtWidgets.QApplication.translate("MainWindow", "Use default", None, -1))
        self.checkBox_annotate_peak_patterns.setText(QtWidgets.QApplication.translate("MainWindow", "Annotate Peak Patterns", None, -1))
        self.checkBox_adduct_library.setText(QtWidgets.QApplication.translate("MainWindow", "Adducts", None, -1))
        self.checkBox_oligomers.setText(QtWidgets.QApplication.translate("MainWindow", "Oligomers", None, -1))
        self.label_pp_ppm_tolerance.setText(QtWidgets.QApplication.translate("MainWindow", "Mass tolerance (ppm):", None, -1))
        self.lineEdit_neutral_losses.setText(QtWidgets.QApplication.translate("MainWindow", "Use default", None, -1))
        self.lineEdit_adduct_library.setText(QtWidgets.QApplication.translate("MainWindow", "Use default", None, -1))
        self.pushButton_adduct_library.setText(QtWidgets.QApplication.translate("MainWindow", "Browse...", None, -1))
        self.pushButton_filename_mf.setText(QtWidgets.QApplication.translate("MainWindow", "Browse...", None, -1))
        self.label_max_mz.setText(QtWidgets.QApplication.translate("MainWindow", "Maximum m/z:", None, -1))
        self.checkBox_mf_pp_rules.setText(QtWidgets.QApplication.translate("MainWindow", "use peak patterns", None, -1))
        self.label_mf_ppm_tolerance.setText(QtWidgets.QApplication.translate("MainWindow", "Mass tolerance (ppm):", None, -1))
        self.comboBox_source_mf.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "https://mfdb.bham.ac.uk", None, -1))
        self.comboBox_source_mf.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Tab-delimited text file", None, -1))
        self.label_filename_mf.setText(QtWidgets.QApplication.translate("MainWindow", "Reference file:", None, -1))
        self.checkBox_heuristic_rules.setText(QtWidgets.QApplication.translate("MainWindow", "Heuristic rules", None, -1))
        self.label_source_mf.setText(QtWidgets.QApplication.translate("MainWindow", "Source:", None, -1))
        self.checkBox_annotate_molecular_formulae.setText(QtWidgets.QApplication.translate("MainWindow", "Annotate Molecular Formulae", None, -1))
        self.pushButton_filename_reference.setText(QtWidgets.QApplication.translate("MainWindow", "Browse...", None, -1))
        self.checkBox_cpds_pp_rules.setText(QtWidgets.QApplication.translate("MainWindow", "use peak patterns", None, -1))
        self.checkBox_filename_reference.setText(QtWidgets.QApplication.translate("MainWindow", "Reference file", None, -1))
        self.label_cpds_ppm_tolerance.setText(QtWidgets.QApplication.translate("MainWindow", "Mass tolerance (ppm):", None, -1))
        self.checkBox_annotate_compounds.setText(QtWidgets.QApplication.translate("MainWindow", "Annotate Compounds / Metabolites", None, -1))
        self.pushButton_summary_filename.setText(QtWidgets.QApplication.translate("MainWindow", "Save as...", None, -1))
        self.checkBox_convert_rt.setText(QtWidgets.QApplication.translate("MainWindow", "Convert RT:", None, -1))
        self.comboBox_annotations_format.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Multiple rows for each feature", None, -1))
        self.comboBox_annotations_format.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Single row for each feature and separate columns", None, -1))
        self.comboBox_annotations_format.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Single row for each feature and merged columns", None, -1))
        self.label_separator.setText(QtWidgets.QApplication.translate("MainWindow", "Separator:", None, -1))
        self.comboBox_convert_rt.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Minutes", None, -1))
        self.comboBox_convert_rt.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Seconds", None, -1))
        self.checkBox_create_summary.setText(QtWidgets.QApplication.translate("MainWindow", "Create summary", None, -1))
        self.checkBox_mz_digits.setText(QtWidgets.QApplication.translate("MainWindow", "Number of digits m/z:", None, -1))
        self.comboBox_separator.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "tab", None, -1))
        self.comboBox_separator.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "comma", None, -1))
        self.label_summary_filename.setText(QtWidgets.QApplication.translate("MainWindow", "Summary:", None, -1))
        self.label_annotations_format.setText(QtWidgets.QApplication.translate("MainWindow", "Annotations:", None, -1))
        self.pushButton_start.setText(QtWidgets.QApplication.translate("MainWindow", "Start", None, -1))
        self.pushButton_cancel.setText(QtWidgets.QApplication.translate("MainWindow", "Cancel", None, -1))
        self.actionExampleData.setText(QtWidgets.QApplication.translate("MainWindow", "Add example data", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))

